image: registry.gitlab.com/jrkerns/pylinac:latest

stages:
  - test
  - coverage


# test script
test:
  stage: test
  before_script:
    # install your own package into the environment
    - python setup.py install
    # attempt to fix DISPLAY variable errors of matplotlib's. See: https://github.com/mwaskom/seaborn/pull/97
    - cp tests_basic/matplotlibrc .
  script:
    - python setup.py test
#    - coverage run --source=pylinac setup.py test

coverage:
  stage: coverage
  before_script:
    # install your own package into the environment
    - python setup.py install
    # attempt to fix DISPLAY variable errors of matplotlib's. See: https://github.com/mwaskom/seaborn/pull/97
    - cp tests_basic/matplotlibrc .
  script:
#    - python setup.py test
    - coverage run --source=pylinac setup.py test
    - coverage report


